"""The Python reader must agree with the Rust writer on the format.

A fixture is generated by the Rust side (`cargo run --example write_fixture`)
and committed under research/fixtures. Here we check the reader parses it into
the expected records, so the two languages cannot drift (roadmap 1.7).
"""

from pathlib import Path

import pytest

from fidus_lab.trace import EventKind, KeyClass, read_trace

FIXTURE = Path(__file__).resolve().parents[2] / "research" / "fixtures" / "sample.fidustr"


def test_reader_round_trips_the_rust_fixture():
    if not FIXTURE.exists():
        pytest.skip("fixture not generated yet (run the Rust example)")
    records = list(read_trace(FIXTURE))
    assert records, "fixture is empty"
    # The fixture encodes, in order: key down (letter), key up (letter),
    # a motion, a wheel notch, a left button down and up.
    kinds = [r.event.kind for r in records]
    assert kinds == [
        EventKind.KEY_DOWN,
        EventKind.KEY_UP,
        EventKind.MOTION,
        EventKind.WHEEL,
        EventKind.BUTTON_DOWN,
        EventKind.BUTTON_UP,
    ]
    assert records[0].event.key_class == KeyClass.LETTER
    assert records[2].event.dx == -5 and records[2].event.dy == 3
    assert records[0].time_us == 1000
    # No record can carry a key code: the type has no such field.
    assert not hasattr(records[0].event, "keycode")


def test_bad_magic_is_rejected(tmp_path):
    p = tmp_path / "bad.fidustr"
    p.write_bytes(b"NOTFIDUS" + b"\x00" * 16)
    with pytest.raises(ValueError):
        list(read_trace(p))
